name: MolTC
channels:
  - pytorch
  - pyg
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - appdirs=1.4.4=pyhd3eb1b0_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bottleneck=1.3.5=py38h7deecbd_0
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2023.5.7=py38h06a4308_0
  - cffi=1.15.1=py38h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py38h06a4308_0
  - comm=0.1.2=py38h06a4308_0
  - cryptography=39.0.1=py38h9ce1e76_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - debugpy=1.5.1=py38h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.13.1=py38h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py38heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py38h06a4308_0
  - importlib-metadata=6.0.0=py38h06a4308_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.19.2=py38hb070fc8_0
  - ipython=8.12.0=py38h06a4308_0
  - jedi=0.18.1=py38h06a4308_1
  - jinja2=3.1.2=py38h06a4308_0
  - joblib=1.1.1=py38h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jupyter_client=8.1.0=py38h06a4308_0
  - jupyter_core=5.3.0=py38h06a4308_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.6.1.9=0
  - libcurand=10.3.2.106=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libidn2=2.3.2=h7f8727e_0
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py38h7f8727e_0
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.2.1=py38h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py38h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.8.4=py38h06a4308_1
  - nltk=3.7=pyhd3eb1b0_0
  - numexpr=2.8.4=py38he184ba9_0
  - numpy=1.24.3=py38h14f4228_0
  - numpy-base=1.24.3=py38h31eccc5_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1t=h7f8727e_0
  - packaging=23.0=py38h06a4308_0
  - pandas=1.5.3=py38h417a72b_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py38h6a678d5_0
  - platformdirs=3.10.0=py38h06a4308_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.36=py38h06a4308_0
  - psutil=5.9.0=py38h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyg=2.3.0=py38_torch_2.0.0_cu117
  - pygments=2.15.1=py38h06a4308_1
  - pyopenssl=23.0.0=py38h06a4308_0
  - pyparsing=3.0.9=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.16=h7a1cb2a_3
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch-cuda=11.7=h778d358_3
  - pytorch-mutex=1.0=cuda
  - pytz=2022.7=py38h06a4308_0
  - pyzmq=25.0.2=py38h6a678d5_0
  - readline=8.2=h5eee18b_0
  - regex=2024.9.11=py38h5eee18b_0
  - scikit-learn=1.2.2=py38h6a678d5_0
  - scipy=1.10.1=py38h14f4228_0
  - setuptools=66.0.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.11.1=py38h06a4308_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.2=py38h5eee18b_0
  - traitlets=5.7.1=py38h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.38.4=py38h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.4.2=h5eee18b_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.11.0=py38h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
#   - pip:
#       - absl-py==2.1.0
#       - accelerate==1.0.0
#       - aiofiles==23.2.1
#       - aiohappyeyeballs==2.4.3
#       - aiohttp==3.10.9
#       - aiosignal==1.3.1
#       - annotated-types==0.7.0
#       - antlr4-python3-runtime==4.9.3
#       - anyio==4.5.2
#       - async-timeout==4.0.3
#       - attrs==24.2.0
#       - blis==0.7.11
#       - braceexpand==0.1.7
#       - catalogue==2.0.10
#       - cloudpathlib==0.16.0
#       - colorama==0.4.6
#       - confection==0.1.5
#       - contourpy==1.1.1
#       - cycler==0.12.1
#       - cymem==2.0.8
#       - datasets==3.1.0
#       - decord==0.6.0
#       - deepspeed==0.15.3
#       - dgl==2.4.0+cu124
#       - dill==0.3.8
#       - einops==0.6.1
#       - et-xmlfile==1.1.0
#       - exceptiongroup==1.2.2
#       - fairscale==0.4.4
#       - fastapi==0.115.4
#       - ffmpy==0.4.0
#       - fonttools==4.54.1
#       - frozenlist==1.4.1
#       - fschat==0.2.36
#       - fsspec==2024.9.0
#       - googledrivedownloader==0.4
#       - gradio==4.44.1
#       - gradio-client==1.3.0
#       - h11==0.14.0
#       - hjson==3.1.0
#       - httpcore==1.0.6
#       - httpx==0.27.2
#       - huggingface-hub==0.25.1
#       - importlib-resources==6.4.5
#       - iniconfig==2.0.0
#       - iopath==0.1.10
#       - isodate==0.7.2
#       - kiwisolver==1.4.7
#       - langcodes==3.4.1
#       - language-data==1.2.0
#       - lightning-utilities==0.11.7
#       - littleutils==0.2.4
#       - marisa-trie==1.2.0
#       - markdown-it-py==3.0.0
#       - markdown2==2.5.1
#       - matplotlib==3.7.5
#       - mdurl==0.1.2
#       - modelscope==1.20.0
#       - msgpack==1.1.0
#       - multidict==6.1.0
#       - multiprocess==0.70.16
#       - murmurhash==1.0.10
#       - nh3==0.2.18
#       - ninja==1.11.1.1
#       - nvidia-cublas-cu12==12.4.2.65
#       - nvidia-cuda-cupti-cu12==12.4.99
#       - nvidia-cuda-nvrtc-cu12==12.4.99
#       - nvidia-cuda-runtime-cu12==12.4.99
#       - nvidia-cudnn-cu12==9.1.0.70
#       - nvidia-cufft-cu12==11.2.0.44
#       - nvidia-curand-cu12==10.3.5.119
#       - nvidia-cusolver-cu12==11.6.0.99
#       - nvidia-cusparse-cu12==12.3.0.142
#       - nvidia-ml-py==12.560.30
#       - nvidia-nccl-cu12==2.20.5
#       - nvidia-nvjitlink-cu12==12.4.99
#       - nvidia-nvtx-cu12==12.4.99
#       - ogb==1.3.6
#       - omegaconf==2.3.0
#       - opencv-python-headless==4.5.5.64
#       - openpyxl==3.1.5
#       - orjson==3.10.11
#       - outdated==0.2.2
#       - pathlib-abc==0.1.1
#       - pathy==0.11.0
#       - peft==0.3.0
#       - pip==24.3.1
#       - pluggy==1.5.0
#       - portalocker==2.10.1
#       - preshed==3.0.9
#       - propcache==0.2.0
#       - protobuf==5.28.2
#       - py-cpuinfo==9.0.0
#       - pyarrow==17.0.0
#       - pycocoevalcap==1.2
#       - pycocotools==2.0.7
#       - pydantic==2.9.2
#       - pydantic-core==2.23.4
#       - pydantic-settings==2.6.1
#       - pydub==0.25.1
#       - pyg-lib==0.4.0+pt24cu124
#       - pytest==8.3.4
#       - python-dotenv==1.0.1
#       - python-multipart==0.0.17
#       - pytorch-lightning==1.9.0
#       - pyyaml==6.0.2
#       - rdflib==7.1.1
#       - rdkit==2022.9.5
#       - requests==2.32.3
#       - rich==13.9.4
#       - rouge-score==0.1.2
#       - ruff==0.7.2
#       - safetensors==0.4.5
#       - salesforce-lavis==1.0.2
#       - semantic-version==2.10.0
#       - sentencepiece==0.2.0
#       - shellingham==1.5.4
#       - shortuuid==1.0.13
#       - smart-open==6.4.0
#       - sniffio==1.3.1
#       - spacy==3.7.2
#       - spacy-legacy==3.0.12
#       - spacy-loggers==1.0.5
#       - srsly==2.4.8
#       - starlette==0.41.2
#       - svgwrite==1.4.3
#       - thinc==8.1.12
#       - tiktoken==0.7.0
#       - timm==0.4.12
#       - tokenizers==0.20.0
#       - tomli==2.2.1
#       - tomlkit==0.12.0
#       - torch==2.4.0+cu124
#       - torch-cluster==1.6.3+pt24cu124
#       - torch-scatter==2.1.2+pt24cu124
#       - torch-sparse==0.6.18+pt24cu124
#       - torch-spline-conv==1.2.2+pt24cu124
#       - torchaudio==2.4.0+cu124
#       - torchmetrics==1.4.2
#       - torchvision==0.19.0+cu124
#       - tqdm==4.67.0
#       - transformers==4.45.2
#       - triton==3.0.0
#       - typer==0.9.4
#       - typing-extensions==4.12.2
#       - urllib3==2.2.3
#       - uvicorn==0.32.0
#       - wasabi==1.1.3
#       - wavedrom==2.0.3.post3
#       - weasel==0.3.4
#       - webdataset==0.2.48
#       - websockets==12.0
#       - xxhash==3.5.0
#       - yacs==0.1.8
#       - yarl==1.14.0
# prefix: /villa/xlx21/anaconda3/envs/MolTC
